apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "podName" . }}
  labels:
    app: web
spec:
  replicas: {{ if eq .Values.environment "prod"}}3{{else}}1{{end}}
  selector:
    matchLabels: 
      {{ include "labels" . | nindent 6}}
  template:
    metadata:
      labels: 
        {{ include "labels" .| nindent 8}}
    spec:
      containers:
        - name: nginx
          image: {{.Values.image.name}}:{{.Values.image.tag}}
          {{- if .Values.service.enabled }}
          ports:
            - containerPort: {{.Values.containerPort.http}}
          {{- end -}}