{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "serviceName" .}}
spec:
  type: {{.Values.service.type}}
  selector: {{ include "labels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: {{.Values.containerPort.http}}
{{- end -}}