## Settings for NGINX Replica Count
##
## @param replicaCount no.of replicas to configure
##replicaCount: 2
environment: test

## Settings for NGINX image
##
## @param image.name Nginx image name to use
## @param image.tag Nginx image tag to use
image:
  name: nginx
  tag: '1.27.0'

## NGINX container ports
##
## @param containerPort.http http port to use
containerPort:
  http: 80

## Settings for NGINX service
##
## @param service.enabled Whether to deploy Service or not
## @param service.type specify type of service
## @param service.port service port to configure
service:
  enabled: true
  type: ClusterIP
  port: 80